resources:
    - repo: self

pool:
    name: Hosted VS2017
    demands: npm

steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
          verbose: false

    - bash: |
          npm install -g vsce
          vsce publish -p $DEPLOY_PAT
      displayName: 'Publish to the marketplace'
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/fix-deploy')))
      env:
        DEPLOY_PAT: $(deployPAT)